# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/src_4a/constraint.xdc

# IP: ip/Input_RAM_B/Input_RAM_B.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Input_RAM_B || ORIG_REF_NAME==Input_RAM_B} -quiet] -quiet

# IP: ip/Input_RAM_A/Input_RAM_A.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Input_RAM_A || ORIG_REF_NAME==Input_RAM_A} -quiet] -quiet
