webtalk_init -webtalk_dir D:/OneDrive - HKUST Connect/HKUST/2023 Fall/ELEC4320/Workspace/Lab2/Lab2.sim/sim_1/behav/xsim/xsim.dir/piano_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Oct 11 10:18:54 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5d0bc8ce-1d25-45e3-8f7e-2dcb716bda14" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "983d3c6b3d0742b998a91a7b39f6933b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i7-12700H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2688 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "9682835603516 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "6.25_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9004_KB" -context "xsim\\usage"
webtalk_transmit -clientid 22934470 -regid "" -xml D:/OneDrive - HKUST Connect/HKUST/2023 Fall/ELEC4320/Workspace/Lab2/Lab2.sim/sim_1/behav/xsim/xsim.dir/piano_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/OneDrive - HKUST Connect/HKUST/2023 Fall/ELEC4320/Workspace/Lab2/Lab2.sim/sim_1/behav/xsim/xsim.dir/piano_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/OneDrive - HKUST Connect/HKUST/2023 Fall/ELEC4320/Workspace/Lab2/Lab2.sim/sim_1/behav/xsim/xsim.dir/piano_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
